name: Create Event Workflow
env:
  application: ${{ github.event.repository.name }}
on:
  create:
  push:
  workflow_dispatch:

jobs:
  test:
    if: ${{ contains(github.ref, 'release') || contains(github.ref, 'hotfix') || contains(github.ref, 'main') }}
    name: Create Event test
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2

      - name: echo shell command
        run: |
          echo ${{ github.event.repository.name }}
          echo ${{ github.ref }}
          echo ${{ contains(github.ref, 'release') }}
          echo ${{ github.event_name }}

  #  Cleanup job after the release. Make sure the `needs` value matches the earlier release job
  cleaner:
    name: Cleanup workspace
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always() }}
    steps:
      - name: Clean runner workspace path
        run: rm -rf "${{ github.workspace }}"
