name: Container Workflow
on: 
  workflow_dispatch:

jobs: 
  docker:
    runs-on: ubuntu-latest
    container: 
      image: node:lts-alpine    
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release

