name: First Workflow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
      - name: echo shell command
        run: echo 'First Work flow'
      - name: RUn multi line command
        run: |
          node -v
          npm -v
      - name: run python command
        shell: python
        run: |
          import platform
          print(platform.processor())
  
  run-windows-command:
    runs-on: windows-latest
    # Default shell for windows is Power Shell
    steps:
      - name: Directory powershell
        run: Get-Location
      - name: Directory 
        run: pwd
        shell: bash

